export default [
    {
        _id: "1",
        name: "Quiz 1",
        description: "This is the first quiz",
        course: "RS101",
        availableDate: "2023-06-01",
        availableUntilDate: "2023-06-30",
        dueDate: "2023-06-15",
        points: 100,
        published: true,
        questions: [],
    },
    {
        _id: "2",
        name: "Quiz 2",
        description: "This is the second quiz",
        course: "RS101",
        availableDate: "2023-07-01",
        availableUntilDate: "2023-07-31",
        dueDate: "2023-07-15",
        points: 150,
        published: false,
        questions: [],
    },
    {
        _id: "3",
        name: "Quiz 3",
        description: "This is the third quiz",
        course: "course2",
        availableDate: "2023-08-01",
        availableUntilDate: "2023-08-31",
        dueDate: "2023-08-15",
        points: 200,
        published: true,
        questions: [],
    },
];
